queue_rules:
  - name: default
    conditions:
      - base=main
      - check-success=build-docs
      - check-success=lint
      - check-success=tests (macos-10.15, 3.6)
      - check-success=tests (macos-10.15, 3.10)
      - check-success=tests (ubuntu-18.04, 3.6)
      - check-success=tests (ubuntu-18.04, 3.10)
      - check-success=tests (windows-2019, 3.6)

pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - base=main
      - author~=^dependabot(|-preview)\[bot\]$
      - check-success=build-docs
      - check-success=lint
      - check-success=tests (macos-10.15, 3.6)
      - check-success=tests (macos-10.15, 3.10)
      - check-success=tests (ubuntu-18.04, 3.6)
      - check-success=tests (ubuntu-18.04, 3.10)
      - check-success=tests (windows-2019, 3.6)
    actions:
      queue:
        name: default
  - name: automatic merge for main when CI passes and reviewed
    conditions:
      - "#approved-reviews-by>=1"
      - base=main
      - check-success=build-docs
      - check-success=lint
      - check-success=tests (macos-10.15, 3.6)
      - check-success=tests (macos-10.15, 3.10)
      - check-success=tests (ubuntu-18.04, 3.6)
      - check-success=tests (ubuntu-18.04, 3.10)
      - check-success=tests (windows-2019, 3.6)
    actions:
      queue:
        name: default
