queue_rules:
  - name: default
    conditions:
      - base=main
      - check-success=build-docs
      - check-success=lint
      - check-success=tests (macos-latest, 3.9)
      - check-success=tests (macos-latest, 3.13)
      - check-success=tests (ubuntu-latest, 3.9)
      - check-success=tests (ubuntu-latest, 3.13)
      - check-success=tests (windows-latest, 3.9)
      - check-success=tests (windows-latest, 3.13)

pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - base=main
      - author~=^dependabot(|-preview)\[bot\]$
      - check-success=build-docs
      - check-success=lint
      - check-success=tests (macos-latest, 3.9)
      - check-success=tests (macos-latest, 3.13)
      - check-success=tests (ubuntu-latest, 3.9)
      - check-success=tests (ubuntu-latest, 3.13)
      - check-success=tests (windows-latest, 3.9)
      - check-success=tests (windows-latest, 3.13)
    actions:
      queue:
        name: default
  - name: automatic merge for main when CI passes and reviewed
    conditions:
      - "#approved-reviews-by>=1"
      - base=main
      - check-success=build-docs
      - check-success=lint
      - check-success=tests (macos-latest, 3.9)
      - check-success=tests (macos-latest, 3.13)
      - check-success=tests (ubuntu-latest, 3.9)
      - check-success=tests (ubuntu-latest, 3.13)
      - check-success=tests (windows-latest, 3.9)
      - check-success=tests (windows-latest, 3.13)
    actions:
      queue:
        name: default
