queue_rules:
  - name: default
    conditions:
      - base=main
      - check-success=build-docs
      - check-success=lint
      - check-success=tests (macos-11, 3.7)
      - check-success=tests (macos-11, 3.11)
      - check-success=tests (ubuntu-20.04, 3.7)
      - check-success=tests (ubuntu-20.04, 3.11)
      - check-success=tests (windows-2022, 3.7)
      - check-success=tests (windows-2022, 3.11)

pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - base=main
      - author~=^dependabot(|-preview)\[bot\]$
      - check-success=build-docs
      - check-success=lint
      - check-success=tests (macos-11, 3.7)
      - check-success=tests (macos-11, 3.11)
      - check-success=tests (ubuntu-20.04, 3.7)
      - check-success=tests (ubuntu-20.04, 3.11)
      - check-success=tests (windows-2022, 3.7)
      - check-success=tests (windows-2022, 3.11)
    actions:
      queue:
        name: default
  - name: automatic merge for main when CI passes and reviewed
    conditions:
      - "#approved-reviews-by>=1"
      - base=main
      - check-success=build-docs
      - check-success=lint
      - check-success=tests (macos-11, 3.7)
      - check-success=tests (macos-11, 3.11)
      - check-success=tests (ubuntu-20.04, 3.7)
      - check-success=tests (ubuntu-20.04, 3.11)
      - check-success=tests (windows-2022, 3.7)
      - check-success=tests (windows-2022, 3.11)
    actions:
      queue:
        name: default
