name: wheel

on:
  push:
    tags:
      - '*'
  release:
    types: [published]

jobs:
  wheel_build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: build wheel
        run: |
          pip install build twine
          python -m build
          twine check dist/*

      - name: upload wheel
        uses: actions/upload-artifact@v3
        with:
          name: wheel-and-sdist
          path: dist/

  wheel_test:
    runs-on: ${{ matrix.os }}
    needs: ['wheel_build']
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.7, 3.8, 3.9, "3.10", "3.11"]

    steps:
      - name: download wheel
        uses: actions/download-artifact@v3
        with:
          name: wheel-and-sdist
          path: dist/

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: install
        run: pip install dist/*.whl

      - name: test
        run: |
          python -c "import demesdraw"
          demesdraw --version
          demes ms -N0 1 -I 2 0 0 0.1 -es 1 1 0.99 -ej 1 3 2 -ej 100 2 1 \
            | demesdraw tubes - /tmp/tubes.svg
          demes ms -N0 100 -G 0.01 -eN 100 1 \
            | demesdraw size_history - /tmp/size_history.svg

  pypi_upload:
    runs-on: ubuntu-20.04
    needs: ['wheel_test']
    steps:
      - name: download wheel
        uses: actions/download-artifact@v3
        with:
          name: wheel-and-sdist
          path: dist/

      - name: publish to test.pypi.org
        if: github.event_name == 'push' && github.ref_type == 'tag'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/

      - name: publish to PyPI
        if: github.event_name == 'release'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
